jwtauth Not working for Django 4.x
- `pyjwt` is package for encoding/decoding jwt protocol
- Installation of drf-jwt failed
```bash
python -m pip install djangorestframework-jwt # package for authentication
python -m pip --upgrade pyjwt                 # to upgrade encode/decode of jwt to 2.6
```
  It is relying on old getuwt package that django doesn't have
```bash
ImportError: Could not import 'rest_framework_jwt.authentication.JSONWebTokenAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ImportError: cannot import name 'ugettext' from 'django.utils.translation' (/home/anel/GitHub/school_enrollment/env/lib/python3.8/site-packages/django/utils/translation/__init__.py).
```

- Solution could be to switch to `DRF-simplejwt` - see branch
`simplejwt-auth`

- Files and references
https://bobbyhadz.com/blog/python-importerror-cannot-import-name-smart-text-from-django-utils-encoding
From author about DRF-jwt 2016 - it is not maitained or less maintained
https://jpadilla.github.io/django-rest-framework-jwt/
https://thinkster.io/tutorials/django-json-api/authentication
https://bobbyhadz.com/blog/python-importerror-cannot-import-name-smart-text-from-django-utils-encoding