Add logic for superuser and update routes
```sql
MariaDB [myEnrollmentDB]> show create table teachersAuth_teacher\G
*************************** 1. row ***************************
       Table: teachersAuth_teacher
Create Table: CREATE TABLE `teachersAuth_teacher` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `last_login` datetime(6) DEFAULT NULL,
  `is_superuser` tinyint(1) NOT NULL,
  `first_name` varchar(150) NOT NULL,
  `last_name` varchar(150) NOT NULL,
  `is_staff` tinyint(1) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `date_joined` datetime(6) NOT NULL,
  `name` varchar(50) NOT NULL,
  `country` varchar(2) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
1 row in set (0.000 sec)

MariaDB [myEnrollmentDB]> insert into teachersAuth_teacher (name, email, password) values ("anelh","anel@eacon.ba","pass1");
ERROR 1364 (HY000): Field 'is_superuser' doesn't have a default value
```

- AbstractBaseUser - nema nista osim last_login() kao defaultni NULL

- Create superuser with existing username
```bash
$ ./manage.py createsuperuser --email a@a
Error: That email is already taken.
Email: a@a
```

- Have done `set foreign_keys_on=0; truncate table; set foreign_key_on=1`:
```sql
MariaDB [myEnrollmentDB]> show create table teachersAuth_teacher\G
*************************** 1. row ***************************
       Table: teachersAuth_teacher
Create Table: CREATE TABLE `teachersAuth_teacher` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `last_login` datetime(6) DEFAULT NULL,
  `is_superuser` tinyint(1) NOT NULL,
  `first_name` varchar(150) NOT NULL,
  `last_name` varchar(150) NOT NULL,
  `is_staff` tinyint(1) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `date_joined` datetime(6) NOT NULL,
  `name` varchar(50) NOT NULL,
  `country` varchar(2) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `username` varchar(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

```
Solution is to override userrname default authentication method
https://stackoverflow.com/questions/55489119/django-db-utils-integrityerror-1062-duplicate-entry-for-key-username

^^^ SOmething else needs to be done:
https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html
https://www.reddit.com/r/django/comments/vo0mwm/typeerror_create_superuser_missing_1_required/
```text
you need to do to set the username to None custom user model and go to option 3. You need to override the UserManager for your custom user model as the create(super)user takes in a username and you need to override those methods to be able to not use the username field when creating users from the console.
```
https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#abstractbaseuser

See here:
https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#a-full-example

Required_filds is used by createsuperuser
https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#django.contrib.auth.models.CustomUser.REQUIRED_FIELDS

Primjer :
```bash
$ ./manage.py createsuperuser --email anel@eacon.ba
First name: Anel
Last name: Husakovic
Password:
Password (again):
Superuser created successfully.
```

- Note that `ordering` can be added to model (see django_rest_framework)
example

Primjer API dati u Readme.md